marvinai/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.loginpage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('CreateReseller/', views.CreateReseller, name='CreateReseller'),
    path('ViewReseller/<str:pk>', views.ViewReseller, name='ViewReseller'),
    path('EditReseller/<str:pk>', views.EditReseller, name='EditReseller'),
    path('DeleteReseller/<str:pk>', views.DeleteReseller, name='DeleteReseller'),

    path('ViewReseller/<str:pk>/dashboard', views.ResellerDashboard, name='ResellerDashboard'),
    path('ViewReseller/<str:pk>/settings', views.ResellerSettings, name='ResellerSettings'),

    path('CreateCustomer/', views.CreateCustomer, name='CreateCustomer'),
    path('ViewCustomer/<str:pk>', views.ViewCustomer, name='ViewCustomer'),
    path('EditCustomer/<str:pk>', views.EditCustomer, name='EditCustomer'),
    path('DeleteCustomer/<str:pk>', views.DeleteCustomer, name='DeleteCustomer'),

    path('ViewCustomer/<str:pk>/dashboard', views.CustomerDashboard, name='CustomerDashboard'),
    path('ViewCustomer/<str:pk>/settings', views.CustomerSettings, name='CustomerSettings'),
    path('ViewCustomer/<str:pk>/training', views.CustomerNLUTraining, name='CustomerNLUTraining'),
    path('post/ajax/nlutrainingupdate', views.NLUTrainingUpdate, name='nlutrainingupdate'),
    path('ViewCustomer/<str:pk>/response', views.CustomerResponse, name='CustomerResponse'),
    path('post/ajax/responseupdate', views.ResponseUpdate, name='responseupdate'),
    path('ViewCustomer/<str:pk>/stories', views.CustomerStories, name='CustomerStories'),
    path('post/ajax/storiesupdate', views.StoriesUpdate, name='storiesupdate'),
    path('ViewCustomer/<str:pk>/domain', views.CustomerDomain, name='CustomerDomain'),
    path('ViewCustomer/<str:pk>/configuration', views.CustomerConfiguration, name='CustomerConfiguration'),
    path('ViewCustomer/<str:pk>/logs', views.CustomerLogs, name='CustomerLogs'),
    path('ViewCustomer/<str:pk>/trainbot', views.CustomerTrainBot, name='CustomerTrainBot'),
    path('post/ajax/trainbot', views.TrainBotBackend, name='trainbot'),
    path('ViewCustomer/<str:pk>/license', views.CustomerLicense, name='CustomerLicense'),
    path('ViewCustomer/<str:pk>/messages', views.CustomerMessages, name='CustomerMessages'),
    path('post/ajax/chathistoryupdate', views.ChatHistoryUpdate, name='chathistoryupdate'),
]

marvinai/marvinai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

marvinai/main/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
from django.conf import settings
from django.contrib.auth import get_user_model
from PIL import Image

from django.db.models.signals import pre_save
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    domain = models.CharField(max_length=40,unique=True)
    email = models.EmailField(max_length=70,blank=True)
    customer = models.BooleanField(default=False)
    reseller = models.BooleanField(default=False)
    logo = models.ImageField(blank=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


class Reseller(MPTTModel):
    #user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete= models.CASCADE)
    Application_name = models.CharField(max_length=40,unique=True)
    reseller_name = models.CharField(max_length=40)
    #reseller_domain = models.CharField(max_length=40)
    #reseller_email = models.EmailField(max_length=70,blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['reseller_name']

    def __str__(self):
        return self.reseller_name


class Customer(models.Model):
    #user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete= models.CASCADE)
    Application_name = models.CharField(max_length=40, unique=True)
    customer_name = models.CharField(max_length=40)
    #customer_domain = models.CharField(max_length=40)
    #customer_email = models.EmailField(max_length=70,blank=True)
    reseller = models.ForeignKey(Reseller, on_delete=models.CASCADE, null=True, blank=True, related_name='cust_children')

    def __str__(self):
        return self.customer_name

marvinai/main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reseller, Customer
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import (authenticate, get_user_model, password_validation,)

class ResellerForm(ModelForm):
    class Meta:
        model = Reseller
        exclude = ["user",'reseller_name','reseller_email']

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        exclude = ["user",'customer_name','customer_email']


class registerForm(forms.ModelForm):
    password = forms.CharField(label = 'Password', widget = forms.PasswordInput(),strip=False,help_text=password_validation.password_validators_help_text_html(),)
    password2 = forms.CharField(label = 'Repeat Password', widget = forms.PasswordInput(),strip=False,help_text="Both Passwords should be same.",)
    #email = forms.EmailField(label = 'Email Address', widget = forms.TextInput())
    domain = forms.CharField(label = 'Domain', widget = forms.TextInput())
    logo = forms.ImageField()
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
        ]

    #Cleaning Method for password Match..........
    def clean_password2(self):
        cd = self.cleaned_data
        if self.cleaned_data.get('password') != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']

    #Cleaning Method for Email Unique..........
    #def clean(self):
    #    if self.cleaned_data.get('email') is None:
    #        raise ValidationError("Enter a valid E-mail Address")
    #    varEmail = self.cleaned_data.get('email').lower()
    #    if User.objects.filter(email = varEmail).count() != 0 :
    #        if not User.objects.get(email = varEmail).is_active :
    #            User.objects.get(email = varEmail).delete()
    #        else:
    #            raise ValidationError(self.cleaned_data.get('email') + "\tAlready Exists.")

marvinai/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from . forms import ResellerForm, CustomerForm, registerForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import logging,traceback
from django.conf import settings
import os
import re, json
import pandas as pd
import subprocess
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import requests
from datetime import date
from datetime import datetime
import datetime
import shutil
from dnsimple import DNSimple #pip install dnsimple
import requests
import fileinput
import subprocess
import threading
import stat
#logger = logging.getlogger('django')
bot_location = "/home/ubuntu/rasabot/"  #Prod: change it to /home/ubuntu/bot/prod

# Create your views here.
#****************************************************#
#                 Login Page View                    #
#****************************************************#
def loginpage(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            url = request.POST.get('urlvalue')
            domainfind=url.split('.')
            domainfindprocess=domainfind[0]
            domain=domainfindprocess[7::]
            print(domain)
            user = authenticate(request, username=username, password=password)
            print(username)
            user_check = Profile.objects.get(user__username=username)
            print(user_check.domain[0])
            print(user)
            if user is not None and user_check.domain[0] == domain  :
                print('se')
                login(request, user)
                return redirect('dashboard')

    return render(request, 'main/login/login.html')

#****************************************************#
#                 Logout View                        #
#****************************************************#
def logoutUser(request):
    logout(request)
    return redirect('login')

#****************************************************#
#           Application Dashboard                    #
#****************************************************#
@login_required(login_url='login')
def dashboard(request):
    ########################### Index logic #########################
    resellers = None
    customers = None
    res=None
    customers_profile=None
    user=Profile.objects.get(user=request.user)
    print(user.domain)
    if user.customer == True :
        customers=Customer.objects.get(user=request.user)
    if user.reseller == True:
        resellers=Reseller.objects.get(user=request.user).get_descendants(include_self=True)

    ########################### Index logic #########################

    context = { 'resellers' : resellers, 'customers' : customers, 'user':user }
    return render(request, 'main/dashboard/index.html', context)

#****************************************************#
#           Create Reseller Account                  #
#****************************************************#
@login_required(login_url='login')
def CreateReseller(request):
    ########################### Index logic #########################
    resellers = None
    customers = None
    res=None
    user=Profile.objects.get(user=request.user)
    if user.customer == True :
        customers=Customer.objects.get(user=request.user)
    if user.reseller == True:
        resellers=Reseller.objects.get(user=request.user).get_descendants(include_self=True)

    ########################### Index logic #########################
    form = ResellerForm()
    form_1 = registerForm()    
    if request.method == 'POST':
        form = ResellerForm(request.POST, request.FILES)
        form_1 = registerForm(request.POST, request.FILES)
        if form.is_valid() & form_1.is_valid():
            user = form_1.save(commit=False)
            user.is_active = True
            user.set_password(form_1.cleaned_data['password2'])
            #user.email = form_1.cleaned_data['email'].lower()
            user.save()
            Reseller_1 = form.save(commit=False) 
            Profile.objects.create(user=user,email=user,domain=form_1.cleaned_data['domain'] ,logo=form_1.cleaned_data['logo'], reseller=True)
            Reseller_1.user=user
            Reseller_1.reseller_name=user.first_name + user.last_name
            #Reseller_1.reseller_email=user.email
            
            form.save()
            
            return redirect('/dashboard/') 
    context = { 'resellers' : resellers, 'customers' : customers, 'user':user, 'form' : form ,'form_1':form_1}
    return render(request, 'main/dashboard/create_reseller.html', context)
    
#****************************************************#
#           View Reseller Account                    #
#****************************************************#
@login_required(login_url='login')
def ViewReseller(request, pk):
    ########################### Index logic #########################
    resellers = None
    customers = None
    res=None
    user=Profile.objects.get(user=request.user)
    if user.customer == True :
        customers=Customer.objects.get(user=request.user)
    if user.reseller == True:
        resellers=Reseller.objects.get(user=request.user).get_descendants(include_self=True)

    ########################### Index logic #########################

    reseller_details = Reseller.objects.get(id=pk)
    context = { 'resellers' : resellers, 'customers' : customers, 'user':user, 'reseller_details' : reseller_details }
    return render(request, 'main/dashboard/view_reseller.html', context)


#****************************************************#
#             Edit Reseller Account                  #
#****************************************************#
@login_required(login_url='login')
def EditReseller(request, pk):
    ########################### Index logic #########################
    resellers = None
    customers = None
    res=None
    user=Profile.objects.get(user=request.user)
    if user.customer == True :
        customers=Customer.objects.get(user=request.user)
    if user.reseller == True:
        resellers=Reseller.objects.get(user=request.user).get_descendants(include_self=True)

    ########################### Index logic #########################

    resellers = Reseller.objects.all()
    customers = Customer.objects.all()
    reseller_details = Reseller.objects.get(id=pk)
    form = ResellerForm(instance=reseller_details)
    context = { 'resellers' : resellers, 
                'customers' : customers, 
                'reseller_details' : reseller_details,
                'form' : form }
    if request.method == 'POST':
        form = ResellerForm(request.POST, instance=reseller_details)
        if form.is_valid():
            form.save()
            return redirect('/dashboard/')
    return render(request, 'main/dashboard/create_reseller.html', context)


#****************************************************#
#           Delete Reseller Account                  #
#****************************************************#
@login_required(login_url='login')
def DeleteReseller(request, pk):
    ########################### Index logic #########################
    resellers = None
    customers = None
    res=None
    user=Profile.objects.get(user=request.user)
    if user.customer == True :
        customers=Customer.objects.get(user=request.user)
    if user.reseller == True:
        resellers=Reseller.objects.get(user=request.user).get_descendants(include_self=True)

    ########################### Index logic #########################

    resellers = Reseller.objects.all()
    customers = Customer.objects.all()
    reseller_details = Reseller.objects.get(id=pk)
    if request.method == 'POST':
        reseller_details.delete()
        return redirect('/dashboard/')
    context = { 'resellers' : resellers, 'customers' : customers, 'user':user, 'reseller_details' : reseller_details }
    return render(request, 'main/dashboard/index.html', context)

#****************************************************#
#           Create Customer Account                  #
#****************************************************#
# @login_required(login_url='login')
# def CreateCustomer(request):
#     ########################### Index logic #########################
#     resellers = None
#     customers = None
#     res=None
#     user=Profile.objects.get(user=request.user)
#     if user.customer == True :
#         customers=Customer.objects.get(user=request.user)
#     if user.reseller == True:
#         resellers=Reseller.objects.get(user=request.user).get_descendants(include_self=True)

#     ########################### Index logic #########################
#     form = CustomerForm()
#     form_1 = registerForm()    
#     if request.method == 'POST':
#         form = CustomerForm(request.POST)
#         form_1 = registerForm(request.POST)
#         if form.is_valid() & form_1.is_valid():
#             user = form_1.save(commit=False)
#             user.is_active = True
#             user.set_password(form_1.cleaned_data['password2'])
#             #user.email = form_1.cleaned_data['email'].lower()
#             user.save()
#             customer_1 = form.save(commit=False) 
#             Profile.objects.create(user=user,email=user,domain=form_1.cleaned_data['domain'] ,logo=form_1.cleaned_data['logo'], customer=True)
#             customer_1.user=user
#             customer_1.customer_name=user.first_name + user.last_name
#             #customer_1.customer_email=user.email

    #         ########################### Create Chatbot #########################
    #         #Prod: Change the number of characater removal based on prod domain name

marvinai/main/templates/main/dashboard/2.html
{% extends 'main/dashboard/index.html' %}

{% block extended_menu %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>{{ error|escape }}</strong>


</div>
{% endfor %}
{% endfor %}
{% endif %}

{% if form_1.errors %}
{% for field in form_1 %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    {% if error == 'A user with that username already exists.' %}
    <strong>A user with this Email already exists.</strong>
    {% elif error == 'This field is required.' %}

    <strong>{{field.name}} is required.</strong>
    {% else %}
    <strong>{{ error|escape }}</strong>
    {% endif %}

</div>
{% endfor %}
{% endfor %}
{% endif %}
                <div class="card-header">
			<i class="fa fa-user"></i><strong class="card-title pl-2">Create New Customer</strong>
		</div>
                <div class="card-body" style="border:1px solid #E5E5E5; background-color:white; overflow:auto;" >
                    <form action="#" method="POST" class="">
                        {% csrf_token %}
                        
                           <!-- <pre style="white-space:pre-wrap; font-size:13px;"> 
                               {{ form.as_p }}
			       {{ form_1.as_p }}
			   </pre> -->

		<!-- ***************** FORM - CustomerForm ************************ -->
              <div class="form-group">
                 <label >Application Name</label>
                <input type="text" name="Application_name" id="id_Application_name"  class="form-control"  placeholder="Application name">
             </div>
             <div class="form-group">
                <label >Reseller</label>
                <select name="reseller" class="form-control">
                    {% for i in form.reseller %}
                      <option  value="{{i.id}}">{{i}}</option>
                   {% endfor %}
              </select>
              </div>

                <!--********************************************************************-->
                <!-- ***************** FORM_1 - registerForm  ************************ -->
             <div class="form-group">
                   <label for="id_email">Email Address</label>
                   <input type="text" name="username" required id="id_username" class="form-control" placeholder="Enter Email">
             </div>

            <div class="form-group">
                  <label>Domain</label>
                  <input type="text" name="domain" id="id_domain" class="form-control" placeholder="domain name">
            </div>

            <div class="form-group">
                  <label>Logo</label>
                 <input type="file" name="logo" id="id_logo" >
            </div>
            <div class="form-group">
                 <label for="id_first_name">First name</label>
                 <input type="text" name="first_name" maxlength="30" id="id_first_name" class="form-control"
                      placeholder="Enter First Name">
            </div>

            <div class="form-group">
                 <label for="id_last_name">Last name</label>
                 <input type="text" name="last_name" maxlength="150" id="id_last_name" class="form-control"
                     placeholder="Enter Last Name">
           </div>

           <div class="form-group">
                <label for="id_password">Password</label>
                <input type="password" name="password" required id="id_password" class="form-control"
                    placeholder="Enter Password">
                <small id="passwordHelpInline" class="text-muted">
                  <ul>
                     <li>Your password can&#39;t be too similar to your other personal information.</li>
                     <li>Your password must contain at least 8 characters.</li>
                     <li>Your password can&#39;t be a commonly used password.</li>
                     <li>Your password can&#39;t be entirely numeric.</li>
                  </ul>
                </small>
           </div>

          <div class="form-group">
               <label for="id_password2">Confirm Password</label>
               <input type="password" name="password2" required id="id_password2" class="form-control"
                   placeholder="Enter Confirm Password">
               <small id="passwordHelpInline" class="text-muted">
                   Both Passwords should be same.
               </small>
         </div>


               <!--********************************************************************-->
                       
                        <div class="form-actions form-group">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>
                </div>
{% endblock %}

marvinai/main/templates/main/dashboard/create_customer.html
{% extends 'main/dashboard/index.html' %}

{% block extended_menu %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>{{ error|escape }}</strong>
  

</div>
{% endfor %}
{% endfor %}
{% endif %}

{% if form_1.errors %}
{% for field in form_1 %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    {% if error == 'A user with that username already exists.' %} 
    <strong>A user with this Email already exists.</strong>
    {% elif error == 'This field is required.' %}
  
    <strong>{{field.name}} is required.</strong>
    {% else %}
    <strong>{{ error|escape }}</strong>
    {% endif %}
   
</div>
{% endfor %}
{% endfor %}
{% endif %}

<div class="card-header">
    <i class="fa fa-home"></i><strong class="card-title pl-2">Create New Customer</strong>
 

</div>
<div class="card-body" style="border:1px solid #E5E5E5; background-color:white; height:80.6vh; overflow:auto;">
    <form action="#" method="post" class="" enctype="multipart/form-data"> 
        {% csrf_token %}
      <!-- {{form.as_p}}
      {{form_1.as_p}} -->






      
 <!-- ***************** FORM - ResellerForm ************************ -->
    <div class="form-group">
            <label >Application Name</label>
            <input type="text" name="Application_name" id="id_Application_name"  class="form-control"  placeholder="Application name">
    </div>
    <div class="form-group">
        <label >Reseller</label>
        <select name="reseller" class="form-control">
            {% for i in form.reseller %}
            <option  value="{{i.id}}">{{i}}</option>
            {% endfor %}
        </select>
</div>
<!--********************************************************************-->
 <!-- ***************** FORM_1 - registerForm  ************************ -->
        <div class="form-group">
            <label for="id_email">Email Address</label>
            <input type="text" name="username" required id="id_username" class="form-control" placeholder="Enter Email">

        </div>
        
        <div class="form-group">
            <label>Domain</label>
            <input type="text" name="domain" id="id_domain" class="form-control" placeholder="domain name">
        </div>
        <!-- <div class="form-group">
            <label for="id_username">Username</label>
            <input type="email" name="username" maxlength="150" required id="id_username" class="form-control"
                placeholder="Enter User">
            <small id="usernameHelpInline" class="text-muted">
                Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
            </small>
        </div>
      -->
      <div class="form-group">
        <label>Logo</label>
        <input type="file" name="logo" id="id_logo" >
    </div>
      
        <div class="form-group">
            <label for="id_first_name">First name</label>
            <input type="text" name="first_name" maxlength="30" id="id_first_name" class="form-control"
                placeholder="Enter First Name">
        </div>

        <div class="form-group">
            <label for="id_last_name">Last name</label>
            <input type="text" name="last_name" maxlength="150" id="id_last_name" class="form-control"
                placeholder="Enter Last Name">
        </div>

        <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" name="password" required id="id_password" class="form-control"
                placeholder="Enter Password">
            <small id="passwordHelpInline" class="text-muted">
                <ul>
                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can&#39;t be a commonly used password.</li>
                    <li>Your password can&#39;t be entirely numeric.</li>
                </ul>
            </small>
        </div>

        <div class="form-group">
            <label for="id_password2">Confirm Password</label>
            <input type="password" name="password2" required id="id_password2" class="form-control"
                placeholder="Enter Confirm Password">
            <small id="passwordHelpInline" class="text-muted">
                Both Passwords should be same.
            </small>
        </div>

  
<!--********************************************************************-->

        <div class="form-actions form-group">
            <button type="submit" class="btn btn-outline-success">Save</button>
        </div>
    </form>
</div>




{% endblock %}